#include<iostream.h>
#include<conio.h>
void main()
{
char m;
cout<<"\n ENTER ANY ALPHABET : \n1)a \n2)e \n3)i \n4)o \n5)u ";
cin>>m;
switch(m)
{
case'1':
cout<<"\n it is a vowel  ";
break;

case'2':
cout<<"\n it is a vowel  ";
break;

case'3':
cout<<"\n it is a vowel  ";
break;

case'4':
cout<<"\n it is a vowel  ";
break;

case'5':
cout<<"\n it is a vowel  ";
break;

default:

cout<<"\n it is a consonent ";
}
getch();
}