#include<iostream.h>
#include<conio.h>
void main()
{

  float n1,n2;

  cout<<"Enter Number 1 : ";
  cin>>n1;

  cout<<"\nEnter Number 2 : ";
  cin>>n2;

  cout<<"\nAddition       : "<<n1<<" + "<<n2<<" = "<<n1+n2;
  cout<<"\nSubtraction    : "<<n1<<" - "<<n2<<" = "<<n1-n2;
  cout<<"\nMultiplication : "<<n1<<" * "<<n2<<" = "<<n1*n2;
  cout<<"\nDivision       : "<<n1<<" / "<<n2<<" = "<<n1/n2;

  getch();
}